name: Auto Update Graphs

on:
  push:
    paths:
      - 'data/*.csv'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib seaborn

      - name: Run analysis script
        run: |
          python analyze.py

      - name: Commit updated graphs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add figures/*.png
          git commit -m "Auto-update graphs from updated CSV" || echo "No changes to commit"
          git push
